name: "Pipeline"
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        with:
          fetch-depth: 0

      - uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-install: true

      - run: "bun install && bun run build"
